// @ts-nocheck
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));

const envPath = resolve(__dirname, '..', '.env');
const vars = {};

if (existsSync(envPath)) {
  const lines = readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eqIndex = trimmed.indexOf('=');
    if (eqIndex === -1) continue;
    const key = trimmed.slice(0, eqIndex).trim();
    let value = trimmed.slice(eqIndex + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    vars[key] = value;
  }
}

const getRaw = (key) => vars[key] ?? process.env[key] ?? '';
const get = (key, fallback = '') =>
  JSON.stringify(vars[key] ?? process.env[key] ?? fallback);

// Fail fast if NG_API_BASE_URL is not set — no silent fallback to a hardcoded URL
const apiBaseUrl = getRaw('NG_API_BASE_URL');
if (!apiBaseUrl) {
  console.error('❌ NG_API_BASE_URL is not set. Add it to your .env file.');
  process.exit(1);
}

const envDir = resolve(__dirname, 'src/environments');
if (!existsSync(envDir)) {
  mkdirSync(envDir, { recursive: true });
}

const devContent = `// AUTO-GENERATED by set-env.mjs — do not edit manually
export const environment = {
  production: false,
  apiBaseUrl: ${get('NG_API_BASE_URL', 'http://localhost:5227')},
  google: {
    clientId: ${get('GOOGLE_CLIENT_ID')},
      // NOTE: dummyClientSecret is required by angular-oauth2-oidc for SPAs.
      // While exposed in the client bundle, this poses minimal security risk:
      // - Google OAuth validates redirect URIs (prevents domain hijacking)
      // - PKCE prevents authorization code interception
      // - Backend validates all tokens independently
    clientSecret: ${get('GOOGLE_CLIENT_SECRET')},
  },
  microsoft: {
    clientId: ${get('MICROSOFT_CLIENT_ID')},
    tenantId: ${get('MICROSOFT_TENANT_ID')},
    apiScope: ${get('MICROSOFT_API_SCOPE')},
  },
};
`;

const prodContent = `// AUTO-GENERATED by set-env.mjs — do not edit manually
export const environment = {
  production: true,
  apiBaseUrl: ${get('NG_API_BASE_URL')},
  google: {
    clientId: ${get('GOOGLE_CLIENT_ID')},
    clientSecret: ${get('GOOGLE_CLIENT_SECRET')},
  },
  microsoft: {
    clientId: ${get('MICROSOFT_CLIENT_ID')},
    tenantId: ${get('MICROSOFT_TENANT_ID')},
    apiScope: ${get('MICROSOFT_API_SCOPE')},
  },
};
`;

writeFileSync(resolve(envDir, 'environment.development.ts'), devContent);
writeFileSync(resolve(envDir, 'environment.ts'), prodContent);

console.log('✅ Environment files generated from .env');